# -*- coding: utf-8 -*-
"""test1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o1kCWTyZEirOQXXNSCAPUK4RyvK-vjEk

#Ques1
"""

def area_calci():
  property= input("Enter the Property name:")
  length= int(input("Enter the length in mts:"))
  width= int(input("Enter the width in mts:"))
  area= length* width
  if 0<= area <= 400:
    print("Area=",area, "sq.mts")
    print("It is a small space")
  elif 401<= area <= 1000:
    print("Area=",area, "sq.mts")
    print("It is a medium space")
  else:
    print("Area=",area, "sq.mts")
    print("It is a large space")

area_calci()

"""#Ques2

"""

def bmi(weight, height):
    return weight / (height ** 2)

# Example usage:
weight = float(input("Enter your weight (in kg): "))
height = float(input("Enter your height (in mts): "))
print("Your BMI is:", bmi(weight, height))
print("Accoring to the report ")
if bmi(weight,height)<16:
  print("You have a Low BMI- Under Weight")
elif 16<bmi(weight,height)<24:
  print("You have a Good BMI, you are normal")
else:
  print("You have higher BMI than Normal BMI -Obese")

"""#Ques 3"""

class students:
    def __init__(self, name, subject1,subject2,subject3,subject4,subject5, grade):
        self.name = name
        self.subject1= subject1
        self.subject2=subject2
        self.subject3=subject3
        self.subject4=subject4
        self.subject5=subject5
        self.grade=grade

    def display_details(self):
        print("Name:", self.name)
        print("Subject1",self.subject1)
        print("Subject2",self.subject2)
        print("Subject3",self.subject3)
        print("Subject4",self.subject4)
        print("Subject5",self.subject5)
        print("Grade:", self.grade)

# Example usage:
student1 = students("Rishi",89,76,78,90,56,"Pass")
student1.display_details()
print("\n\n\n")
student2=students("Priya",56,98,90,87,87,"Pass")
student2.display_details()

"""#Ques 4"""

def p_message():
    age = int(input("Enter your age: "))

    if age <= 10:
        message = "You're just a kid!"
    elif 11 <= age <= 18:
        message = "Welcome, teenager!"
    elif 18<= age <= 59:
        message = "Welcome, adult!"
    else:
      message = "Welcome, you Senior Citizen"

    print(message)

p_message()

"""#Ques 5"""



"""#Ques 6"""

def passwordfromfile(filename):
    try:
        with open(filename, 'r') as file:
            return file.read().strip()
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found.")
        return None

def password_prompt(filename):
    correct_password = passwordfromfile(filename)
    if correct_password is None:
        return

    while True:
        password = input("Enter the password: ")
        if password == correct_password:
            print("Correct password entered. Access granted!")
            break
        else:
            print("Incorrect password. Please try again.")

# Call the function to start the password prompt
filename = "/content/password.txt"  # Change this to the path of your password file
password_prompt(filename)

"""#Ques 7

"""

def customer_feedback():
  name= input("Enter your name:")
  service=int(input("Enter a score (0-5) for our service:"))
  variety=int(input("Enter a score (0-5) for our service:"))
  cleanliness=int(input("Enter a score (0-5) for our service:"))
  salesperson=int(input("Enter a score (0-5) for our service:"))
  hospitality=int(input("Enter a score (0-5) for our service:"))
  billing=int(input("Enter a score (0-5) for our service:"))
  average_score= round((service+variety+cleanliness+salesperson+hospitality+billing)/6,323
                       )
  print("Average_score of your given feedback:",average_score)

  try:
    if 0.10<=average_score<=1.5:
      print("The service is poor")
    elif 1.5<=average_score<=3.5:
      print("The service is good")
    elif 3.5<=average_score<=5:
      print("The service is excellent")
    else:
      print("No feedback Received")
  except:
    pass

customer_feedback()

"""#Ques 8"""



"""#Ques 9"""



"""#Ques 10"""

class banking:
  def loan():
    pass

"""#Ques 11"""



"""#Ques 12"""

def calculator():
  n1=int(input("Enter the first number:"))
  n2=int(input("enter the second number:"))
  n=0
  operator= input("Choose any operator +,-,*,/")
  try:
    if operator=='+':
      return n1+n2
    elif operator=='-':
      return n1-n2
    elif operator=='*':
      return n1*n2
    elif operator=='/':
      return n1/n2
    else:
      print("No operation found")
  except ZeroDivisionError:
    print("Denominator cant be zero")


calculator()

"""#Ques 13"""



"""#Ques 14

"""



"""#Ques 15"""

